upgrade to consul 1.8.3 and systemd

diff --git a/modules/install-dnsmasq/install-dnsmasq b/modules/install-dnsmasq/install-dnsmasq
--- a/modules/install-dnsmasq/install-dnsmasq
+++ b/modules/install-dnsmasq/install-dnsmasq
@@ -6,6 +6,10 @@
 
 set -e
 
+# Import the appropriate bash commons libraries
+readonly BASH_COMMONS_DIR="/opt/gruntwork/bash-commons"
+readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
 readonly DEFAULT_CONSUL_DOMAIN="consul"
 readonly DEFAULT_CONSUL_IP="127.0.0.1"
 readonly DEFAULT_CONSUL_DNS_PORT=8600
@@ -13,7 +17,14 @@ readonly DEFAULT_CONSUL_DNS_PORT=8600
 readonly DNS_MASQ_CONFIG_DIR="/etc/dnsmasq.d"
 readonly CONSUL_DNS_MASQ_CONFIG_FILE="$DNS_MASQ_CONFIG_DIR/10-consul"
 
-readonly SCRIPT_NAME="$(basename "$0")"
+if [[ ! -d "$BASH_COMMONS_DIR" ]]; then
+  echo "ERROR: this script requires that bash-commons is installed in $BASH_COMMONS_DIR. See https://github.com/gruntwork-io/bash-commons for more info."
+  exit 1
+fi
+
+source "$BASH_COMMONS_DIR/assert.sh"
+source "$BASH_COMMONS_DIR/log.sh"
+source "$BASH_COMMONS_DIR/os.sh"
 
 function print_usage {
   echo
@@ -32,49 +43,12 @@ function print_usage {
   echo "  install-dnsmasq"
 }
 
-function log {
-  local -r level="$1"
-  local -r message="$2"
-  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
-}
-
-function log_info {
-  local -r message="$1"
-  log "INFO" "$message"
-}
-
-function log_warn {
-  local -r message="$1"
-  log "WARN" "$message"
-}
-
-function log_error {
-  local -r message="$1"
-  log "ERROR" "$message"
-}
-
-function assert_not_empty {
-  local -r arg_name="$1"
-  local -r arg_value="$2"
-
-  if [[ -z "$arg_value" ]]; then
-    log_error "The value for '$arg_name' cannot be empty"
-    print_usage
-    exit 1
-  fi
-}
-
-function has_apt_get {
-  [[ -n "$(command -v apt-get)" ]]
-}
-
 function install_dnsmasq {
   local -r consul_ip="$1"
 
   log_info "Installing Dnsmasq"
 
-  if $(has_apt_get); then
+  if $(os_is_ubuntu); then
     sudo apt-get update -y
     sudo apt-get install -y dnsmasq
   else
@@ -100,12 +74,28 @@ bind-interfaces
 EOF
 }
 
+function write_consul_config {
+  local -r consul_domain="$1"
+  local -r consul_ip="$2"
+  local -r consul_port="$3"
+
+  log_info "Configuring Dnsmasq to forward lookups of the '$consul_domain' domain to $consul_ip:$consul_port in $CONSUL_DNS_MASQ_CONFIG_FILE"
+  mkdir -p "$DNS_MASQ_CONFIG_DIR"
+
+  sudo tee "$CONSUL_DNS_MASQ_CONFIG_FILE" <<EOF
+# Enable forward lookup of the '$consul_domain' domain:
+server=/${consul_domain}/${consul_ip}#${consul_port}
+listen-address=${consul_ip}
+bind-interfaces
+EOF
+}
+
 function install {
   local consul_domain="$DEFAULT_CONSUL_DOMAIN"
   local consul_ip="$DEFAULT_CONSUL_IP"
   local consul_dns_port="$DEFAULT_CONSUL_DNS_PORT"
 
-  while [[ $# > 0 ]]; do
+  while [[ $# -gt 0 ]]; do
     local key="$1"
 
     case "$key" in
